# Generated by Django 5.2.3 on 2025-06-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MajorStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('applications', models.IntegerField()),
                ('acceptances', models.IntegerField()),
            ],
            options={
                'unique_together': {('campus', 'major', 'year')},
            },
        ),
    ]
